[server]
listen_addr = "127.0.0.1:8443"
health_addr = "127.0.0.1:8081"

[tls]
chain_path = "certs/server-chain.pem"
key_path = "certs/server.key"
root_ca_path = "certs/rootca.crt"

[upstream]
backends = [
    "http://127.0.0.1:18888",
    "http://127.0.0.1:17777",
    "http://127.0.0.1:19999",
]

[logging]
level = "info"
format = "text"
detailed_logging = false
log_response_body = true
max_logged_body_size = 1048576

[health_check]
interval_seconds = 10
connection_timeout_ms = 1000

# Vendor-specific OID configuration
# Add your hardware vendors here
[[vendors.vendor]]
name = "Acme Energy Systems"
oid = "1.3.6.1.4.1.12345"
device_type = "meter"

[[vendors.vendor]]
name = "Solar Innovations Inc"
oid = "1.3.6.1.4.1.54321"
device_type = "der_device"

[[vendors.vendor]]
name = "EV Charging Solutions"
oid = "1.3.6.1.4.1.98765"
device_type = "ev_charger"

[[vendors.vendor]]
name = "Smart Grid Technologies"
oid = "1.3.6.1.4.1.11111"
device_type = "gateway"

# You can add more vendors as needed
# Valid device_type values:
# - der_device (Distributed Energy Resource)
# - meter (Smart Meter)
# - gateway (Communication Gateway)
# - aggregator (DER Aggregator)
# - ev_charger (Electric Vehicle Charger)
# - thermostat (Smart Thermostat)
# - custom (Custom Device Type)
